# Site settings
title: Imad Qureshi
email: Imadqureshi2@Gmail.com
description: >- # used by seo meta and the atom feed
  Data Scientist/Dashboard Consultant specializing in data visualization and analytics solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imadq.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Social media profiles
github_username: imadq
linkedin_username: imad-qureshi-811854208

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/ 